# Generated by Django 4.2.7 on 2023-12-03 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_plate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='photo',
        ),
        migrations.AlterField(
            model_name='carclientform',
            name='car_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='car_clients', to='cars.car'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carimg', to='cars.car')),
            ],
        ),
    ]
