# Generated by Django 4.2.7 on 2023-12-05 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_car_photo_alter_carclientform_car_id_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='capa',
            field=models.ImageField(default='null', upload_to='cars/'),
        ),
    ]
