# Generated by Django 4.2.7 on 2023-12-05 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carclientform',
            name='car_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_clients', to='cars.car'),
        ),
    ]
