# Generated by Django 4.2.7 on 2023-12-09 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_carclientform_car_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='ano',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='cambio',
            field=models.CharField(choices=[('Automatico', 'Automático'), ('Manual', 'Manual')], default='Manual', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='cor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='direcao',
            field=models.CharField(choices=[('Hidráulica', 'Hidráulica'), ('Elétrica', 'Elétrica'), ('Mecânica', 'Mecânica')], default='Hidráulica', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='km_atual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carclientform',
            name='car_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='car_clients', to='cars.car'),
        ),
    ]
