# Generated by Django 4.2.7 on 2023-12-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_car_ano_car_cambio_car_cor_car_direcao_car_km_atual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='ano',
        ),
        migrations.AlterField(
            model_name='car',
            name='factory_year',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='model_year',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
    ]
