# Generated by Django 4.2.7 on 2023-12-12 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_car_cambio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='factory_year',
            new_name='ano',
        ),
        migrations.RemoveField(
            model_name='car',
            name='model_year',
        ),
    ]
