# Generated by Django 4.2.7 on 2023-12-19 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_rename_factory_year_car_ano_remove_car_model_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='carclientform',
            name='mensagem',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='carclientform',
            name='car_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='car_clients', to='cars.car'),
        ),
    ]
