# Generated by Django 4.2.7 on 2023-12-28 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_alter_car_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='acessories',
        ),
        migrations.AddField(
            model_name='car',
            name='acessoriess',
            field=models.ManyToManyField(blank=True, to='cars.acessories'),
        ),
    ]
