# Generated by Django 4.2.7 on 2023-12-28 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_rename_brand_car_brandd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='acessoriess',
        ),
        migrations.RemoveField(
            model_name='car',
            name='brandd',
        ),
        migrations.AddField(
            model_name='car',
            name='acessories',
            field=models.ManyToManyField(to='cars.acessories'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='car_brand', to='cars.brand'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carclientform',
            name='car_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_clients', to='cars.car'),
        ),
    ]
